export const AllIndianBanks = [
    // --- सार्वजनिक क्षेत्र के बैंक (Public Sector Banks - 12) ---
    { name: "State Bank of India", code: "SBI" },
    { name: "Punjab National Bank", code: "PNB" },
    { name: "Bank of Baroda", code: "BOB" },
    { name: "Canara Bank", code: "CNRB" },
    { name: "Union Bank of India", code: "UBI" },
    { name: "Bank of India", code: "BOI" },
    { name: "Indian Bank", code: "IBANK" },
    { name: "Central Bank of India", code: "CBI" },
    { name: "Indian Overseas Bank", code: "IOB" },
    { name: "UCO Bank", code: "UCO" },
    { name: "Bank of Maharashtra", code: "BOM" },
    { name: "Punjab & Sind Bank", code: "PSB" },

    // --- निजी क्षेत्र के बैंक (Private Sector Banks - 21) ---
    { name: "HDFC Bank", code: "HDFC" },
    { name: "ICICI Bank", code: "ICICI" },
    { name: "Axis Bank", code: "AXIS" },
    { name: "Kotak Mahindra Bank", code: "KOTAK" },
    { name: "IndusInd Bank", code: "INDUS" },
    { name: "Yes Bank", code: "YES" },
    { name: "Federal Bank", code: "FED" },
    { name: "IDFC First Bank", code: "IDFC" },
    { name: "South Indian Bank", code: "SIB" },
    { name: "Bandhan Bank", code: "BANDHAN" },
    { name: "RBL Bank", code: "RBL" },
    { name: "Karnataka Bank", code: "KRNK" },
    { name: "Karur Vysya Bank", code: "KVB" },
    { name: "Tamilnad Mercantile Bank", code: "TMB" },
    { name: "City Union Bank", code: "CUB" },
    { name: "Jammu & Kashmir Bank", code: "JKB" },
    { name: "Dhanlaxmi Bank", code: "DHAN" },
    { name: "IDBI Bank", code: "IDBI" },
    { name: "DCB Bank", code: "DCB" },
    { name: "Nainital Bank", code: "NAINITAL" },
    { name: "CSB Bank", code: "CSB" },

    // --- स्मॉल फाइनेंस बैंक (Small Finance Banks - 12) ---
    { name: "AU Small Finance Bank", code: "AU" },
    { name: "Equitas Small Finance Bank", code: "EQUITAS" },
    { name: "Ujjivan Small Finance Bank", code: "UJJIVAN" },
    { name: "Jana Small Finance Bank", code: "JANA" },
    { name: "Capital Small Finance Bank", code: "CAPITAL" },
    { name: "ESAF Small Finance Bank", code: "ESAF" },
    { name: "Utkarsh Small Finance Bank", code: "UTKARSH" },
    { name: "Suryoday Small Finance Bank", code: "SURYODAY" },
    { name: "North East Small Finance Bank", code: "NESFB" },
    { name: "Unity Small Finance Bank", code: "UNITY" },
    { name: "Shivalik Small Finance Bank", code: "SHIVALIK" },
    { name: "Fincare Small Finance Bank", code: "FINCARE" },

    // --- पेमेंट्स बैंक (Payments Banks) ---
    { name: "Airtel Payments Bank", code: "AIRTEL" },
    { name: "India Post Payments Bank", code: "IPPB" },
    { name: "Fino Payments Bank", code: "FINO" },
    { name: "Paytm Payments Bank", code: "PAYTM" },
    { name: "Jio Payments Bank", code: "JIO" },
    { name: "NSDL Payments Bank", code: "NSDL" },

    // --- क्षेत्रीय ग्रामीण बैंक (RRBs - 43) ---
    { name: "Andhra Pragathi Grameena Bank", code: "APGB" },
    { name: "Andhra Pradesh Grameena Vikas Bank", code: "APGVB" },
    { name: "Arunachal Pradesh Rural Bank", code: "APRB" },
    { name: "Assam Gramin Vikash Bank", code: "AGVB" },
    { name: "Bangiya Gramin Vikash Bank", code: "BGVB" },
    { name: "Baroda Gujarat Gramin Bank", code: "BGGB" },
    { name: "Baroda Rajasthan Kshetriya Gramin Bank", code: "BRKGB" },
    { name: "Baroda UP Bank", code: "BUPB" },
    { name: "Chaitanya Godavari Grameena Bank", code: "CGGB" },
    { name: "Chhattisgarh Rajya Gramin Bank", code: "CRGB" },
    { name: "Dakshin Bihar Gramin Bank", code: "DBGB" },
    { name: "Ellaquai Dehati Bank", code: "EDB" },
    { name: "Himachal Pradesh Gramin Bank", code: "HPGB" },
    { name: "J&K Grameena Bank", code: "JKGB" },
    { name: "Jharkhand Rajya Gramin Bank", code: "JRGB" },
    { name: "Karnataka Gramin Bank", code: "KGB" },
    { name: "Karnataka Vikas Grameena Bank", code: "KVGB" },
    { name: "Kerala Gramin Bank", code: "KLGB" },
    { name: "Madhya Pradesh Gramin Bank", code: "MPGB" },
    { name: "Madhyanchal Gramin Bank", code: "MGB" },
    { name: "Maharashtra Gramin Bank", code: "MAHGB" },
    { name: "Manipur Rural Bank", code: "MRB" },
    { name: "Meghalaya Rural Bank", code: "MERY" },
    { name: "Mizoram Rural Bank", code: "MZRB" },
    { name: "Nagaland Rural Bank", code: "NGRB" },
    { name: "Odisha Gramya Bank", code: "OGB" },
    { name: "Paschim Banga Gramin Bank", code: "PBGB" },
    { name: "Prathama UP Gramin Bank", code: "PUPGB" },
    { name: "Puduvai Bharathiar Grama Bank", code: "PBGBK" },
    { name: "Punjab Gramin Bank", code: "PGB" },
    { name: "Rajasthan Marudhara Gramin Bank", code: "RMGB" },
    { name: "Saptagiri Grameena Bank", code: "SGB" },
    { name: "Sarva Haryana Gramin Bank", code: "SHGB" },
    { name: "Saurashtra Gramin Bank", code: "SAGB" },
    { name: "Tamil Nadu Grama Bank", code: "TNGB" },
    { name: "Telangana Grameena Bank", code: "TGB" },
    { name: "Tripura Gramin Bank", code: "TGYB" },
    { name: "Utkal Grameen Bank", code: "UGB" },
    { name: "Uttar Bihar Gramin Bank", code: "UBGB" },
    { name: "Uttarakhand Gramin Bank", code: "UKGB" },
    { name: "Uttarbanga Kshetriya Gramin Bank", code: "UKGXB" },
    { name: "Vidharbha Konkan Gramin Bank", code: "VKGB" },

    // --- प्रमुख सहकारी बैंक (Scheduled Co-operative Banks) ---
    { name: "Saraswat Co-operative Bank", code: "SRCB" },
    { name: "Cosmos Co-operative Bank", code: "COSMOS" },
    { name: "Shamrao Vithal Co-operative Bank (SVC)", code: "SVCB" },
    { name: "Abhyudaya Co-operative Bank", code: "ABHY" },
    { name: "Bharat Co-operative Bank", code: "BHARAT" },
    { name: "Janata Sahakari Bank (Pune)", code: "JANATA" },
    { name: "Kalupur Commercial Co-operative Bank", code: "KALUPUR" },
    { name: "NKGSB Co-operative Bank", code: "NKGSB" },
    { name: "TJSB Sahakari Bank", code: "TJSB" },
    { name: "The Maharashtra State Co-operative Bank", code: "MSCB" },
    { name: "Ahmedabad Mercantile Co-op Bank", code: "AMCB" },
    { name: "Akola District Central Co-operative Bank", code: "ADCC" },
    { name: "Apna Sahakari Bank", code: "APNA" },
    { name: "Bassein Catholic Co-operative Bank", code: "BCCB" },
    { name: "Citizen Credit Co-operative Bank", code: "CITIZEN" },
    { name: "Dombivli Nagari Sahakari Bank (DNS Bank)", code: "DNSB" },
    { name: "Gopinath Patil Parsik Janata Sahakari Bank", code: "GPPB" },
    { name: "Greater Bombay Co-operative Bank", code: "GBCB" },
    { name: "Jalgaon People's Co-operative Bank", code: "JPCB" },
    { name: "Kalyan Janata Sahakari Bank", code: "KJSB" },
    { name: "Mehsana Urban Co-operative Bank", code: "MUCB" },
    { name: "New India Co-operative Bank", code: "NICB" },
    { name: "Nutan Nagarik Sahakari Bank", code: "NNSB" },
    { name: "Punjab & Maharashtra Co-operative Bank", code: "PMC" },
    { name: "Rajkot Nagarik Sahakari Bank", code: "RNSB" },
    { name: "Surat People's Co-operative Bank", code: "SPCB" },
    { name: "Zoroastrian Co-operative Bank", code: "ZCB" },

    // --- विदेशी बैंक (Major Foreign Banks) ---
    { name: "Citibank", code: "CITI" },
    { name: "HSBC Bank", code: "HSBC" },
    { name: "Standard Chartered Bank", code: "SCB" },
    { name: "DBS Bank India", code: "DBS" },
    { name: "Deutsche Bank", code: "DB" },
    { name: "Barclays Bank", code: "BARC" },
    { name: "Bank of America", code: "BOFA" },
    { name: "JP Morgan Chase Bank", code: "JPM" },
    { name: "Societe Generale", code: "SOCGEN" },
    { name: "Shinhan Bank", code: "SHINHAN" },
    { name: "BNP Paribas", code: "BNP" },
    { name: "Mizuho Bank", code: "MIZUHO" },
    { name: "MUFG Bank", code: "MUFG" },
    { name: "Qatar National Bank", code: "QNB" },
    { name: "American Express", code: "AMEX" }
];